### PR TITLE
[luab] Rename namespace lua to luab

### PR DESCRIPTION
**Pull request by wateret**
Due to namespace collision, this commit renames namespace `lua` to
`luab`.

### CODE REVIEW

**Comment by wateret** [comment]
Related issue : #106

**Comment by wateret** [comment]
@sjsinju Could you please check if this works?

**Comment by sjsinju** [comment]
@wateret OK I will.

**Comment by sjsinju** [comment]
building works well... but when I run the game, I can just see the screen with blank black screen.



Mouse event on the part of my drawn red circle is only working to exit the game.
I hate `Mojave` !!! :( (I should have updated it later..)

**Comment by wateret** [comment]
@sjsinju Have you tried `brew upgrade sdl2`?

**Comment by wateret** [comment]
@sjsinju Let's keep talking on #106. I will merge this.

**Pull request merged**
