### PR TITLE
Introduce ItemDetailView

### PR DESCRIPTION
**Pull request by sjsinju**
Related : #100 

This commit introduces ItemDetailView that can be shown detailed item description.

- Introduce ItemDetailView class
- Change ItemIconView parameter to get equipment object for showing detailed item info
- Add TODO comment for showing ItemDetailView in tooltip

### CODE REVIEW

**Comment by wateret** [comment]
The code looks good to me.

**Comment by wateret** [comment]
@sjsinju And please check your git user configuration. It does not lead to your github account.

**Comment by sjsinju** [comment]
@wateret OK. :) Let me apply it

**Comment by wateret** [comment]
For this PR I see the wrong author email address for those two. If I merge this, probably github does not count this as your contribution. Would it be OK? or if you want to fix it, please squash commit with the email address registered in your github account.

```
commit 95a6a10f5c8b6a8824ce1c0506429c50c02ce859 (HEAD -> pr-114)
Author: sjsujin.kim <sjsujin.kim@naver.com>
Date:   Sun Oct 7 22:48:07 2018 +0900

    fix format

commit eeb8cd42f56a6be4c2d760cb48e7ba3bc2dc01ff
Author: SUJIN KIM <sujinkim@SUJINui-MacBook-Pro.local>
Date:   Sun Oct 7 00:47:40 2018 +0900

    Introduce ItemDetailView

    This commit introduces ItemDetailView that can be shown detailed item description.

    - Introduce ItemDetailView class
    - Change ItemIconView parameter to get equipment object for showing detailed item info
    - Add TODO comment for showing ItemDetailView in tooltip
```

**Comment by wateret** [comment]
👍

**Pull request merged**
