### PR TITLE
Modify for Ubuntu 14.04 version

### PR DESCRIPTION
**Pull request by llFreetimell**
In Ubuntu 14.04 version, there are problems as below.

1. There is no clang-format package.
```
seok@ubuntu:~/mengde$ ./ci/install_deps_ubuntu.sh 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package clang-format
```

2. Requested version of boost is 1.55, not 1.52. And also libboost-all-dev package in Ubuntu 14.04 is 1.54 version.
```
...
CMake Error at /usr/share/cmake-2.8/Modules/FindBoost.cmake:1131 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.54.0

  Boost include path: /usr/include

  Detected version of Boost is too old.  Requested version was 1.55 (or newer).
Call Stack (most recent call first):
  CMakeLists.txt:37 (find_package)
...
```

Therefore, I modified to use clang-format-3.4 and boost1.55 in Ubuntu 14.04 environment.
After modifying, I did build test and confirmed the result program runs well.

### CODE REVIEW

**Comment by llFreetimell** [comment]
After I finished build in Ubuntu 14.04, I failed to play game, specifically when I click the 'example' button. And then I updated to Ubuntu 16.04, I succeeded. I don't know it is problem of Ubuntu version or my mistake.

**Comment by wateret** [comment]
@llFreetimell Have you tried changing the version of boost? Or could you try with 1.52 by changing this line? https://github.com/wateret/mengde/blob/master/CMakeLists.txt#L37

Maybe 1.52 could be just enough :)

**Comment by llFreetimell** [comment]
I was supposed to try by changing that line, but dependencies of boost are twisted. I will try it ASAP.

**Comment by llFreetimell** [comment]
Do you still have willing to support Ubuntu 14.04? After some changes applied, specific minimum versions of `cmake` and `clang-format` is required.
If you want to do so, modifications of build document and other codes are needed I think.

**Comment by wateret** [comment]
@llFreetimell BTW, changing required boost version is still acceptable. With either way:

- Change the version of required boost to 1.55 from the document file
- If you can check if 1.52 version of boost works, you can update required boost to 1.52 from CMake file. https://github.com/wateret/mengde/blob/master/CMakeLists.txt#L43

**Comment by llFreetimell** [comment]
I close this PR since we talked in offline.

**Pull request closed without merging**
