### PR TITLE
Build gui module as shared library

### PR DESCRIPTION
**Pull request by seanshpark**
This will separate gui as a shared library

### CODE REVIEW

**Comment by seanshpark** [comment]
For #21

**Comment by seanshpark** [comment]
```
  "mengde::core::CmdEndTurn::CmdEndTurn()", referenced from:
      mengde::gui::app::ControlView::ControlView(...)
```
`core` is referenced from `gui`. Need to spearate `core` first

**Comment by wateret** [comment]
@seanshpark Please, resolve conflicts.

**Comment by seanshpark** [comment]
Conflict resolved :)

**Comment by wateret** [comment]
Thanks!

**Pull request merged**
